import type { Metadata } from "next";
import { Inter } from "next/font/google";
import cx from "classnames";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/favicon.ico",
        href: "/favicon.ico",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/favicon-dark.ico",
        href: "/favicon-dark.ico",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cx(inter.className, "antialiased")}>
        <Header />
        <div className="fixed bg-gradient-to-br from-transparent to-gradient-color rounded-full opacity-32 blur-3xl top-[-25%] left-1/2 transform -translate-x-1/2 h-[37.18rem] max-w-[90vw] w-[50rem]" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
