import type { Metadata } from "next";
import { Inter } from "next/font/google";
import cx from "classnames";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/icon.ico",
        href: "/icon.ico",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/icon-dark.ico",
        href: "/icon-dark.ico",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={cx(inter.className, "antialiased")}>{children}</body>
    </html>
  );
}
