import fs from "fs";
import path from "path";
import matter from "gray-matter";

const contentDir = path.join(process.cwd(), "src/content");
const outputPath = path.join(process.cwd(), "src/config/posts.ts");

const posts = fs
  .readdirSync(contentDir)
  .filter((file) => file.endsWith(".mdx"))
  .map((file) => {
    const filePath = path.join(contentDir, file);
    const fileContents = fs.readFileSync(filePath, "utf8");
    const { data } = matter(fileContents);
    return { ...data, slug: file.replace(".mdx", "") };
  })
  .filter((post) => !post.hidden)
  .map((post) => post.slug);

const fileContent = `
// This file is automatically generated - do not edit manually
export const posts = ${JSON.stringify(posts, null, 2)} as const;
`;

fs.writeFileSync(outputPath, fileContent);
